apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my_webapp
spec:
  selector:
    app: my_webapp
  type: NodePort
  ports:
    - nodePort: 31098
      port: 81
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy

spec:
  replicas: 2
  selector:
    matchLabels:
      app: my_webapp 
  template:
    metadata:
      name: myweb-deploypod
      labels: 
        app: my_webapp 
    spec:
      containers:
      - name: myweb-depcon
        image: ankita0610/webserver-html:v2 
